weights: yolov5/yolov5s-seg.pt
cfg: yolov5/models/segment/yolov5m-seg.yaml
data: train_data/20ch_minmax_3/configs/fold_1.yaml
hyp:
  lr0: 0.0005
  lrf: 0.0005
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.4
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0
  hsv_s: 0
  hsv_v: 0
  degrees: 0
  translate: 0.1
  scale: 0.5
  shear: 0
  perspective: 0.0
  flipud: 0.5
  fliplr: 0.5
  mosaic: 0.2
  mixup: 0.0
  copy_paste: 0.0
epochs: 300
batch_size: 128
imgsz: 256
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '5'
multi_scale: false
single_cls: false
optimizer: AdamW
sync_bn: false
workers: 8
project: yolov5/runs/train-seg
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 300
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
mask_ratio: 4
no_overlap: true
save_dir: yolov5/runs/train-seg/exp10
